/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lcaatyirzeljlirzjbdq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjYWF0eWlyemVsamxpcnpqYmRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE0Nzg3MDUsImV4cCI6MjA5NzA1NDcwNX0.9S3CwomMNYeUzBx0JS-HdV17Bvm3pNW2f4rpG-Nrd8I"