import { createContext, useContext, useState, ReactNode } from "react";

type Language = "ru" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Navigation
    "nav.home": "Главная",
    "nav.about": "О клане",
    "nav.requirements": "Требования",
    "nav.apply": "Подать заявку",
    
    // Home Page
    "home.welcome": "Добро пожаловать в клан",
    "home.subtitle": "Элитный клан в The Strongest Battlegrounds. Покажи свою силу и стань частью легенды!",
    "home.apply": "Подать заявку",
    "home.requirements": "Требования",
    "home.stats.members": "Участников клана",
    "home.stats.raids": "Побед в рейдах",
    "home.stats.level": "Средний уровень",
    "home.whyUs": "Почему выбирают нас?",
    "home.feature1.title": "🎮 Активное комьюнити",
    "home.feature1.desc": "Играем вместе каждый день, проводим тренировки и рейды. Всегда найдется кто-то онлайн!",
    "home.feature2.title": "⚔️ Участие в рейдах",
    "home.feature2.desc": "Представляем клан на рейдах и занимаем топовые позиции в рейтингах.",
    "home.feature3.title": "⚡ Обучение и развитие",
    "home.feature3.desc": "Опытные игроки помогут освоить сложные комбо и техники. Прокачайся быстрее с нами!",
    "home.feature4.title": "👥 Дружная атмосфера",
    "home.feature4.desc": "Мы не просто команда, мы семья. Уважаем каждого участника и ценим вклад в развитие клана.",
    "home.cta.title": "Готов присоединиться?",
    "home.cta.desc": "Докажи, что ты достоин носить тег UR. Заполни заявку и начни свой путь к славе!",
    "home.cta.button": "Подать заявку сейчас",
    
    // About Page
    "about.title": "О клане",
    "about.subtitle": "Мы — элитное сообщество игроков The Strongest Battlegrounds, стремящихся к победам и совершенству в каждом бою.",
    "about.history.title": "📜 Наша история",
    "about.history.p1": "Клан UR был основан в 2024 году группой энтузиастов, объединенных одной целью — стать лучшими в The Strongest Battlegrounds. С самого начала мы придерживались принципов честной игры, взаимопомощи и постоянного развития.",
    "about.history.p2": "За это время наш клан вырос с 5 участников до более чем 50 активных членов. Мы участвовали во множестве рейдов, заняли призовые места и заработали репутацию одного из самых сильных кланов в игре.",
    "about.history.p3": "Сегодня UR — это не просто клан, это семья игроков, которые помогают друг другу расти, делятся опытом и вместе празднуют каждую победу.",
    "about.values": "Наши ценности",
    "about.value1.title": "Честность",
    "about.value1.desc": "Мы играем честно и требуем того же от всех участников. Никаких читов, эксплойтов или нечестных методов.",
    "about.value2.title": "Мастерство",
    "about.value2.desc": "Постоянное совершенствование навыков — наш приоритет. Каждая тренировка делает нас сильнее.",
    "about.value3.title": "Единство",
    "about.value3.desc": "Мы поддерживаем друг друга в любой ситуации. Вместе мы сила, которую невозможно остановить.",
    "about.value4.title": "Победа",
    "about.value4.desc": "Мы стремимся к победе, но уважаем соперников и учимся на каждом поражении.",
    "about.achievements": "🏆 Наши достижения",
    "about.achievement1.title": "Официальный клан",
    "about.achievement1.desc": "Признан администрацией игры",
    "about.achievement2.title": "ТОП-5",
    "about.achievement2.desc": "Рейтинг лучших кланов сервера",
    "about.achievement3.title": "100+ побед",
    "about.achievement3.desc": "В рейдах и клановых войнах",
    "about.achievement4.title": "Активное комьюнити",
    "about.achievement4.desc": "Более 50 участников онлайн ежедневно",
    "about.leadership": "👑 Руководство клана",
    "about.leader": "Лидер клана",
    "about.leader.desc": "Основатель и главный стратег",
    "about.coleader": "Со-лидер",
    "about.coleader.desc": "Тренер и организатор рейдов",
    "about.coowner": "Со-овнер",
    "about.coowner.desc": "Администратор и управление",
    
    // Requirements Page
    "req.title": "Требования для вступления",
    "req.subtitle": "Мы ищем сильных и преданных игроков. Убедись, что соответствуешь нашим стандартам!",
    "req.mandatory": "Обязательные требования",
    "req.mandatory1.title": "10000+ киллов",
    "req.mandatory1.desc": "Минимум 10000 убийств в игре. Это показывает твой опыт и преданность игре.",
    "req.mandatory2.title": "Активная игра",
    "req.mandatory2.desc": "Минимум 3-4 дня в неделю онлайн. Мы ценим активных участников, которые могут помочь клану.",
    "req.mandatory3.title": "Discord",
    "req.mandatory3.desc": "Обязательное наличие Discord для коммуникации с командой. Здесь мы координируем тренировки и рейды.",
    "req.mandatory4.title": "Возраст 13+",
    "req.mandatory4.desc": "Мы принимаем игроков от 13 лет. Важна адекватность и умение работать в команде.",
    "req.mandatory5.title": "Знание основных комбо",
    "req.mandatory5.desc": "Ты должен владеть базовыми комбинациями и механиками игры. Новичков мы можем обучить, но основы нужно знать.",
    "req.desired": "Желательные навыки",
    "req.desired1.title": "Опыт в PvP",
    "req.desired1.desc": "Опыт участия в дуэлях и клановых войнах будет большим плюсом.",
    "req.desired2.title": "Владение несколькими стилями",
    "req.desired2.desc": "Умение играть разными персонажами и адаптироваться к ситуации.",
    "req.desired3.title": "Позитивное отношение",
    "req.desired3.desc": "Умение поддерживать команду, не токсичность и желание помогать другим.",
    "req.forbidden": "Строго запрещено",
    "req.forbidden1.title": "Читы и эксплойты",
    "req.forbidden1.desc": "Любое использование читов приведет к немедленному исключению из клана.",
    "req.forbidden2.title": "Токсичность",
    "req.forbidden2.desc": "Оскорбления, грубость и неуважение к другим участникам недопустимы.",
    "req.forbidden3.title": "Неактивность",
    "req.forbidden3.desc": "Отсутствие более 2 недель без предупреждения может привести к исключению.",
    "req.forbidden4.title": "Измена клану",
    "req.forbidden4.desc": "Шпионаж, передача информации другим кланам и участие в нескольких кланах одновременно.",
    "req.process": "📋 Процесс отбора",
    "req.process1.title": "Подача заявки",
    "req.process1.desc": "Заполни форму на странице \"Подать заявку\" с информацией о себе.",
    "req.process2.title": "Рассмотрение",
    "req.process2.desc": "Руководство клана рассмотрит твою заявку в течение 1-3 дней.",
    "req.process3.title": "Тестовые матчи",
    "req.process3.desc": "Если заявка одобрена, тебе предложат сыграть несколько матчей с членами клана.",
    "req.process4.title": "Финальное решение",
    "req.process4.desc": "После тестовых матчей руководство примет финальное решение о вступлении.",
    "req.cta": "Соответствуешь всем требованиям?",
    
    // Apply Page
    "apply.title": "Подать заявку в клан UR",
    "apply.subtitle": "Заполни форму ниже, и мы свяжемся с тобой в ближайшее время!",
    "apply.success.title": "Заявка отправлена!",
    "apply.success.desc": "Спасибо за интерес к нашему клану. Мы рассмотрим твою заявку в течение 1-3 дней и свяжемся с тобой через Discord.",
    "apply.success.note": "Не забудь проверить Discord и принять запрос в друзья от руководства клана UR!",
    "apply.success.again": "Отправить еще одну заявку",
    "apply.roblox": "Roblox никнейм",
    "apply.roblox.placeholder": "Введи свой Roblox никнейм",
    "apply.discord": "Discord юзернейм",
    "apply.discord.placeholder": "Например: username#1234",
    "apply.age": "Возраст",
    "apply.age.placeholder": "Сколько тебе лет?",
    "apply.kills": "Количество убийств",
    "apply.kills.placeholder": "Сколько у тебя киллов?",
    "apply.experience": "Опыт игры",
    "apply.experience.select": "Выбери опыт",
    "apply.experience.newbie": "Новичок (меньше месяца)",
    "apply.experience.beginner": "Начинающий (1-3 месяца)",
    "apply.experience.intermediate": "Средний (3-6 месяцев)",
    "apply.experience.advanced": "Продвинутый (6-12 месяцев)",
    "apply.experience.expert": "Эксперт (более года)",
    "apply.playtime": "Сколько часов в неделю можешь играть?",
    "apply.playtime.placeholder": "Например: 10-15 часов",
    "apply.mainChar": "Основной персонаж/стиль",
    "apply.mainChar.placeholder": "Например: Garou, Saitama, Genos",
    "apply.whyJoin": "Почему хочешь вступить в UR?",
    "apply.whyJoin.placeholder": "Расскажи немного о себе и почему хочешь присоединиться к нашему клану...",
    "apply.submit": "Отправить заявку",
    "apply.info": "Важная информация",
    "apply.info1": "• Все поля обязательны для заполнения",
    "apply.info2": "• Рассмотрение заявки займет 1-3 дня",
    "apply.info3": "• Мы свяжемся с тобой через Discord, указанный в заявке",
    "apply.info4": "• После одобрения заявки тебе нужно будет пройти тестовые матчи",
    "apply.info5": "• Ложная информация приведет к автоматическому отклонению заявки",
    
    // Profile Page
    "nav.profile": "Профиль",
    "profile.title": "Мой профиль",
    "profile.create.title": "Создать профиль",
    "profile.create.subtitle": "Заполни информацию о себе и создай свой профиль игрока",
    "profile.roblox": "Roblox никнейм",
    "profile.roblox.placeholder": "Введи свой Roblox никнейм",
    "profile.discord": "Discord юзернейм",
    "profile.discord.placeholder": "Например: username#1234",
    "profile.kills": "Количество убийств",
    "profile.kills.placeholder": "Сколько у тебя киллов?",
    "profile.mainChar": "Основной персонаж",
    "profile.mainChar.placeholder": "Например: Garou, Saitama, Genos",
    "profile.playtime": "Часов игры в неделю",
    "profile.playtime.placeholder": "Например: 10-15",
    "profile.bio": "О себе",
    "profile.bio.placeholder": "Расскажи немного о себе...",
    "profile.save": "Сохранить профиль",
    "profile.edit": "Редактировать профиль",
    "profile.stats.title": "Статистика",
    "profile.info.title": "Информация",
    "profile.status": "Статус",
    "profile.status.member": "Участник клана",
    "profile.status.applicant": "Кандидат",
    "profile.member.since": "В клане с",
    "profile.rank": "Ранг",
    "profile.rank.leader": "Лидер",
    "profile.rank.coleader": "Со-лидер",
    "profile.rank.coowner": "Со-овнер",
    "profile.rank.moderator": "Модератор",
    "profile.rank.admin": "Администратор",
    "profile.rank.member": "Участник",
    "profile.admin.title": "Управление рангами",
    "profile.admin.password": "Пароль администратора",
    "profile.admin.password.placeholder": "Введите пароль",
    "profile.admin.unlock": "Разблокировать",
    "profile.admin.locked": "Только лидер и со-лидер могут изменять ранги",

    // Applications Page
    "nav.applications": "Заявки",
    "applications.title": "Управление заявками",
    "applications.subtitle": "Просмотр и обработка заявок в клан",
    "applications.loading": "Загрузка...",
    "applications.access.denied": "Доступ запрещен",
    "applications.access.message": "Только лидер и со-овнер могут просматривать и принимать заявки",
    "applications.pending": "Ожидают",
    "applications.accepted": "Приняты",
    "applications.rejected": "Отклонены",
    "applications.list": "Список заявок",
    "applications.empty": "Нет заявок",
    "applications.details": "Детали заявки",
    "applications.select": "Выберите заявку для просмотра",
    "applications.submitted": "Подана",
    "applications.status.pending": "Ожидает",
    "applications.status.accepted": "Принята",
    "applications.status.rejected": "Отклонена",
    "applications.accept": "Принять",
    "applications.reject": "Отклонить",
    "applications.delete": "Удалить",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About",
    "nav.requirements": "Requirements",
    "nav.apply": "Apply",
    
    // Home Page
    "home.welcome": "Welcome to clan",
    "home.subtitle": "Elite clan in The Strongest Battlegrounds. Show your strength and become part of the legend!",
    "home.apply": "Apply Now",
    "home.requirements": "Requirements",
    "home.stats.members": "Clan Members",
    "home.stats.raids": "Raid Victories",
    "home.stats.level": "Average Level",
    "home.whyUs": "Why Choose Us?",
    "home.feature1.title": "🎮 Active Community",
    "home.feature1.desc": "We play together every day, conduct training and raids. There's always someone online!",
    "home.feature2.title": "⚔️ Raid Participation",
    "home.feature2.desc": "We represent the clan in raids and occupy top positions in rankings.",
    "home.feature3.title": "⚡ Training & Development",
    "home.feature3.desc": "Experienced players will help master complex combos and techniques. Level up faster with us!",
    "home.feature4.title": "👥 Friendly Atmosphere",
    "home.feature4.desc": "We're not just a team, we're a family. We respect every member and value their contribution to the clan.",
    "home.cta.title": "Ready to Join?",
    "home.cta.desc": "Prove that you're worthy to wear the UR tag. Fill out the application and start your path to glory!",
    "home.cta.button": "Apply Now",
    
    // About Page
    "about.title": "About Clan",
    "about.subtitle": "We are an elite community of The Strongest Battlegrounds players, striving for victory and excellence in every battle.",
    "about.history.title": "📜 Our History",
    "about.history.p1": "UR Clan was founded in 2024 by a group of enthusiasts united by one goal — to become the best in The Strongest Battlegrounds. From the very beginning, we adhered to the principles of fair play, mutual assistance and constant development.",
    "about.history.p2": "During this time, our clan has grown from 5 members to more than 50 active members. We participated in many raids, took prizes and earned a reputation as one of the strongest clans in the game.",
    "about.history.p3": "Today UR is not just a clan, it's a family of players who help each other grow, share experience and celebrate every victory together.",
    "about.values": "Our Values",
    "about.value1.title": "Honesty",
    "about.value1.desc": "We play fair and require the same from all members. No cheats, exploits or unfair methods.",
    "about.value2.title": "Mastery",
    "about.value2.desc": "Constant skill improvement is our priority. Every training session makes us stronger.",
    "about.value3.title": "Unity",
    "about.value3.desc": "We support each other in any situation. Together we are a force that cannot be stopped.",
    "about.value4.title": "Victory",
    "about.value4.desc": "We strive for victory, but respect opponents and learn from every defeat.",
    "about.achievements": "🏆 Our Achievements",
    "about.achievement1.title": "Official Clan",
    "about.achievement1.desc": "Recognized by game administration",
    "about.achievement2.title": "TOP-5",
    "about.achievement2.desc": "Server's best clans rating",
    "about.achievement3.title": "100+ victories",
    "about.achievement3.desc": "In raids and clan wars",
    "about.achievement4.title": "Active Community",
    "about.achievement4.desc": "More than 50 members online daily",
    "about.leadership": "👑 Clan Leadership",
    "about.leader": "Clan Leader",
    "about.leader.desc": "Founder and chief strategist",
    "about.coleader": "Co-Leader",
    "about.coleader.desc": "Trainer and raid organizer",
    "about.coowner": "Co-Owner",
    "about.coowner.desc": "Administrator and management",
    
    // Requirements Page
    "req.title": "Join Requirements",
    "req.subtitle": "We're looking for strong and dedicated players. Make sure you meet our standards!",
    "req.mandatory": "Mandatory Requirements",
    "req.mandatory1.title": "10000+ kills",
    "req.mandatory1.desc": "Minimum 10000 kills in game. This shows your experience and dedication to the game.",
    "req.mandatory2.title": "Active Play",
    "req.mandatory2.desc": "Minimum 3-4 days per week online. We value active members who can help the clan.",
    "req.mandatory3.title": "Discord",
    "req.mandatory3.desc": "Discord is mandatory for team communication. Here we coordinate training and raids.",
    "req.mandatory4.title": "Age 13+",
    "req.mandatory4.desc": "We accept players aged 13 and over. Maturity and ability to work in a team are important.",
    "req.mandatory5.title": "Basic Combo Knowledge",
    "req.mandatory5.desc": "You must know basic combinations and game mechanics. We can train beginners, but you need to know the basics.",
    "req.desired": "Desired Skills",
    "req.desired1.title": "PvP Experience",
    "req.desired1.desc": "Experience in duels and clan wars will be a big plus.",
    "req.desired2.title": "Multiple Style Mastery",
    "req.desired2.desc": "Ability to play different characters and adapt to the situation.",
    "req.desired3.title": "Positive Attitude",
    "req.desired3.desc": "Ability to support the team, non-toxicity and willingness to help others.",
    "req.forbidden": "Strictly Forbidden",
    "req.forbidden1.title": "Cheats and Exploits",
    "req.forbidden1.desc": "Any use of cheats will result in immediate expulsion from the clan.",
    "req.forbidden2.title": "Toxicity",
    "req.forbidden2.desc": "Insults, rudeness and disrespect towards other members are unacceptable.",
    "req.forbidden3.title": "Inactivity",
    "req.forbidden3.desc": "Absence for more than 2 weeks without warning may result in expulsion.",
    "req.forbidden4.title": "Clan Betrayal",
    "req.forbidden4.desc": "Espionage, information transfer to other clans and participation in multiple clans simultaneously.",
    "req.process": "📋 Selection Process",
    "req.process1.title": "Application",
    "req.process1.desc": "Fill out the form on the \"Apply\" page with information about yourself.",
    "req.process2.title": "Review",
    "req.process2.desc": "Clan leadership will review your application within 1-3 days.",
    "req.process3.title": "Test Matches",
    "req.process3.desc": "If the application is approved, you will be asked to play several matches with clan members.",
    "req.process4.title": "Final Decision",
    "req.process4.desc": "After test matches, leadership will make the final decision on admission.",
    "req.cta": "Meet all requirements?",
    
    // Apply Page
    "apply.title": "Apply to UR Clan",
    "apply.subtitle": "Fill out the form below and we'll contact you soon!",
    "apply.success.title": "Application Sent!",
    "apply.success.desc": "Thank you for your interest in our clan. We will review your application within 1-3 days and contact you via Discord.",
    "apply.success.note": "Don't forget to check Discord and accept the friend request from UR clan leadership!",
    "apply.success.again": "Submit Another Application",
    "apply.roblox": "Roblox Username",
    "apply.roblox.placeholder": "Enter your Roblox username",
    "apply.discord": "Discord Username",
    "apply.discord.placeholder": "Example: username#1234",
    "apply.age": "Age",
    "apply.age.placeholder": "How old are you?",
    "apply.kills": "Kill Count",
    "apply.kills.placeholder": "How many kills do you have?",
    "apply.experience": "Game Experience",
    "apply.experience.select": "Select experience",
    "apply.experience.newbie": "Newbie (less than a month)",
    "apply.experience.beginner": "Beginner (1-3 months)",
    "apply.experience.intermediate": "Intermediate (3-6 months)",
    "apply.experience.advanced": "Advanced (6-12 months)",
    "apply.experience.expert": "Expert (more than a year)",
    "apply.playtime": "How many hours per week can you play?",
    "apply.playtime.placeholder": "Example: 10-15 hours",
    "apply.mainChar": "Main Character/Style",
    "apply.mainChar.placeholder": "Example: Garou, Saitama, Genos",
    "apply.whyJoin": "Why do you want to join UR?",
    "apply.whyJoin.placeholder": "Tell us a bit about yourself and why you want to join our clan...",
    "apply.submit": "Submit Application",
    "apply.info": "Important Information",
    "apply.info1": "• All fields are required",
    "apply.info2": "• Application review takes 1-3 days",
    "apply.info3": "• We will contact you via Discord specified in the application",
    "apply.info4": "• After approval, you will need to pass test matches",
    "apply.info5": "• False information will result in automatic rejection",
    
    // Profile Page
    "nav.profile": "Profile",
    "profile.title": "My Profile",
    "profile.create.title": "Create Profile",
    "profile.create.subtitle": "Fill in your information and create your player profile",
    "profile.roblox": "Roblox Username",
    "profile.roblox.placeholder": "Enter your Roblox username",
    "profile.discord": "Discord Username",
    "profile.discord.placeholder": "Example: username#1234",
    "profile.kills": "Kill Count",
    "profile.kills.placeholder": "How many kills do you have?",
    "profile.mainChar": "Main Character",
    "profile.mainChar.placeholder": "Example: Garou, Saitama, Genos",
    "profile.playtime": "Hours per week",
    "profile.playtime.placeholder": "Example: 10-15",
    "profile.bio": "About Me",
    "profile.bio.placeholder": "Tell us a bit about yourself...",
    "profile.save": "Save Profile",
    "profile.edit": "Edit Profile",
    "profile.stats.title": "Statistics",
    "profile.info.title": "Information",
    "profile.status": "Status",
    "profile.status.member": "Clan Member",
    "profile.status.applicant": "Applicant",
    "profile.member.since": "Member Since",
    "profile.rank": "Rank",
    "profile.rank.leader": "Leader",
    "profile.rank.coleader": "Co-Leader",
    "profile.rank.coowner": "Co-Owner",
    "profile.rank.moderator": "Moderator",
    "profile.rank.admin": "Administrator",
    "profile.rank.member": "Member",
    "profile.admin.title": "Rank Management",
    "profile.admin.password": "Administrator Password",
    "profile.admin.password.placeholder": "Enter password",
    "profile.admin.unlock": "Unlock",
    "profile.admin.locked": "Only leader and co-leader can change ranks",

    // Applications Page
    "nav.applications": "Applications",
    "applications.title": "Application Management",
    "applications.subtitle": "View and process clan applications",
    "applications.loading": "Loading...",
    "applications.access.denied": "Access Denied",
    "applications.access.message": "Only leader and co-owner can view and process applications",
    "applications.pending": "Pending",
    "applications.accepted": "Accepted",
    "applications.rejected": "Rejected",
    "applications.list": "Applications List",
    "applications.empty": "No applications",
    "applications.details": "Application Details",
    "applications.select": "Select an application to view",
    "applications.submitted": "Submitted",
    "applications.status.pending": "Pending",
    "applications.status.accepted": "Accepted",
    "applications.status.rejected": "Rejected",
    "applications.accept": "Accept",
    "applications.reject": "Reject",
    "applications.delete": "Delete",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("ru");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
